import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import java.util.List;
import java.util.ArrayList;

import java.lang.System;

/*
 * This Java source file was generated by the Gradle 'init' task.
 * import javax.persistence.GenerationType
 */
public class App {

    public static void main(String[] args) {
    }
}
